### ISSUE TITLE
Error in tests - RegressionDemoTest

### ISSUE THREAD

**Issue by tarrow** [petermr/ami-plugin#6]
Failure on running mvn install when running tests.

23278 [main] DEBUG org.xmlcml.ami2.plugins.RegressionDemoTest  - --sp.species --context 35 50 --sp.type binomial genus genussp  -q  target/multiple/bmc_trials_15_1_511  target/multiple/http_www.trialsjournal.com_content_16_1_1  -i scholarly.html
2.0.1
23281 [main] ERROR org.xmlcml.cmine.args.DefaultArgProcessor  - File does not exist: /home/tom/src/contentmine/ami-plugin/target/multiple/bmc_trials_15_1_511
23281 [main] ERROR org.xmlcml.cmine.args.DefaultArgProcessor  - File does not exist: /home/tom/src/contentmine/ami-plugin/target/multiple/http_www.trialsjournal.com_content_16_1_1
23281 [main] ERROR org.xmlcml.cmine.args.DefaultArgProcessor  - Cannot create output: --project or --output must be given
2.0.1
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.597 sec <<< FAILURE!

**Comment by petermr** [comment]
Doesn't fail in current release
